version: '3.4'
services:
  db:
    container_name: ${DB_NAME}
    image: postgres:alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    expose:
      - ${DB_PORT}

  web:
    container_name: web
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db