# Generated by Django 4.1.7 on 2023-03-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.menu",
            ),
            preserve_default=False,
        ),
    ]
