# Generated by Django 4.1.7 on 2023-03-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_item_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name_plural": "menus"},
        ),
        migrations.AlterField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childrens",
                to="menu.item",
            ),
        ),
    ]
