# Generated by Django 4.1.7 on 2023-03-03 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_menu_options_alter_item_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name_plural": "menu"},
        ),
    ]
