# Generated by Django 4.1.7 on 2023-03-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_menu_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="menu.item",
            ),
        ),
    ]
